name: practice
on:
  push:
    branch: main
  pull_request:
    branch: main
jobs:
  mypractice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "hello world"
    
